### ISSUE TITLE
Execute C# dll using RBP

### ISSUE THREAD

**Issue by Bright-Brave** [bvn-architecture/RevitBatchProcessor#105]
Hi,
I got the following info from FAQ, and have made some effort to run my own dll which aims at exporting rvt to another 3d format using task script.
> You can execute functions in a C# DLL using a python task script!

This is  part of my code in the task script.
``` python
sys.path.append(r'C:\Users\CBY\Desktop\Exportor4RBP\Exportor4RBP\bin\Debug')

clr.AddReference("Exportor4RBP.dll")

# the 'Exportor4RBP' project uses the third party dll, not sure whether it is necessary.
clr.AddReference("Newtonsoft.Json.dll")

from Exportor4RBP import Exportor

doc = revit_script_util.GetScriptDocument()

# static method to start export
result = Exportor.Start(doc)
```
In addition, the dll written in C# involves `Transaction`, `IExportContext` of Revit API, as well as some third party dlls, such as `Newtonsoft.Json`.

I run this using RBP successfully, but I got nothing. After debuging, I found that it only run into the `Start()` and `Finish()` method in the [IExportContext](https://apidocs.co/apps/revit/2019/00dd06f6-d262-fd7f-5886-6ae200cb64aa.htm) cs. Maybe I should turn on the `OpenInUI` because the export is based on the 3D view. However, it failed again.

I have no idea about this. Anyone can help?

Best Regards.

**Comment by punderscoresmithuk** [comment]
Hi @Bright-Brave 

This isn't really an RBP issue, it's more a Revit API question. 

My suggestion would be to try and set this up on a single model in Dynamo or Revit Python shell or pyRevit and execute your above python script from there. See if you can get it going on one model. It's likely a speedier debug loop than running through RBP everytime.

Also, ensure all your third party dlls are in the same folder as your Exportor4RBP.dll

I think you might get more attention to your question on the Dynamo or Revit API forums where they are monitored alot more frequently.

Apologies, that's not entirely helpful but you'll probably get more traction there if you include more code (such as your interface implementation), screenshots, error messages, stack trace etc.

Cheers, Pete

**Comment by Bright-Brave** [comment]
@punderscoresmithuk Thanks for your reply.

I just made some mistake in my C# dll, and now it works well.
