### ISSUE TITLE
Files in B360

### ISSUE THREAD

**Issue by Thrasso00** [bvn-architecture/RevitBatchProcessor#106]
Hi,
I have some problems when the files are in B360. Can we use this tool with files that are in B360?
My idea is to use RBP on several files but some are on my server and some are in B360 design. 
I am going to run a dynamo script once a week using RBP. As a workaround I have tried to download the files from b360 with a batch file but I have not succeeded.

Have you considered an alternative in case RBP doesn't work with files in b360?

Regards.

**Comment by punderscoresmithuk** [comment]
Hi @Thrasso00,

Pardon the stupid question but are you following the instructions in the repo to work with BIM360 files?

There's no problem with RBP using a mix of files I don't believe. Can you paste a screenshot or copy of your file list?

Some other things to consider:

- Do you still have permissions etc to access the BIM360 project? 
- The GUIDs are all ok? 
- When you say you downloaded the files from B360 with a batch file, but it has not succeded, what did you try to do sorry? I don't understand

Cheers, Pete

**Comment by Thrasso00** [comment]
Hi @punderscoresmithuk,

I am sorry but I have not found the instructions for the B360 files. Could you give me the url of those instructions?
Here is a screenshot with the file list and the message I get.

![image](https://user-images.githubusercontent.com/51405393/229484162-69b88af2-b1b2-4565-81bf-342acf42793b.png)

**Comment by andydandy74** [comment]
https://github.com/bvn-architecture/RevitBatchProcessor/wiki/Revit-Batch-Processor-FAQ

**Comment by Thrasso00** [comment]
Hi,
Thank you.
Do you know a way to get the project and file GUID?
I think I can get the project Id from the 360's URL. However, I have some difficulties in obtaining the file GUID.

**Comment by punderscoresmithuk** [comment]
It looks like you're trying to open a model from a location on your Autodesk docs drive, is that right? That's not how RBP has been designed to handle cloud hosted models.

You can get the model and project GUIDs by using the methods in the ModelPath class

https://www.revitapidocs.com/2021.1/f214cb44-8350-054e-821a-53571769f236.htm

Or alternatively through Autodesk Forge. Or just watch your collaboration cache as you save the file when you have it open

Cheers, Pete
