### ISSUE TITLE
Revit 2024 support

### ISSUE THREAD

**Issue by maciejwypych** [bvn-architecture/RevitBatchProcessor#109]
Hi,
I've added Revit 2024 support, you can merge it from my fork https://github.com/maciejwypych/RevitBatchProcessor

**Comment by infeeeee** [comment]
Can you share a build/release?

**Comment by indexzeroxyz** [comment]
I would'nt mind this either :)
Thanks guys

**Comment by juanrossxo** [comment]
@maciejwypych it appears the 2024 fork you added has issues with creating local models from a central path.  
I'm a newb, so I haven't been able to figure out why the batch_rvt_util classes aren't being found by the revit_script_host.py file? 
The fork works for non-workshared files, just not workshared ones.. 

[BatchRvt_20240216_100505_551.txt](https://github.com/bvn-architecture/RevitBatchProcessor/files/14314666/BatchRvt_20240216_100505_551.txt)
16/02/2024 10:05:05 : 
16/02/2024 10:05:05 : Session ID: <2024-02-16T18:05:05.551Z>
16/02/2024 10:05:05 : 
16/02/2024 10:05:05 : Log File:
16/02/2024 10:05:05 : 
16/02/2024 10:05:05 : 	C:\Users\...\AppData\Local\BatchRvt\BatchRvt_20240216_100505_551.log
16/02/2024 10:05:05 : 
16/02/2024 10:05:05 : Task Script:
16/02/2024 10:05:05 : 
16/02/2024 10:05:05 : 	V:\...\Dynamo\Archive\Test Task Scheduler PDF\.to_PDF.dyn
16/02/2024 10:05:05 : 
16/02/2024 10:05:05 : Revit Processing mode:
16/02/2024 10:05:05 : 
16/02/2024 10:05:05 : 	Batch Revit File processing
16/02/2024 10:05:05 : 
16/02/2024 10:05:05 : Central File Processing mode:
16/02/2024 10:05:05 : 
16/02/2024 10:05:05 : 	Create New Local
16/02/2024 10:05:05 : 
16/02/2024 10:05:05 : 	Local File will be deleted after processing.
16/02/2024 10:05:05 : 
16/02/2024 10:05:05 : 	Worksets Configuration: Open All
16/02/2024 10:05:05 : 
16/02/2024 10:05:05 : Reading Revit File list:
16/02/2024 10:05:05 : 
16/02/2024 10:05:05 : 	C:\Users\....xlsx
16/02/2024 10:05:14 : 
16/02/2024 10:05:14 : 
16/02/2024 10:05:14 : Revit Files for processing (2):
16/02/2024 10:05:14 : 
	V:\PROJECT DATA\2021\...S22.rvt
	File exists: YES
	File size: 55.57MB
	Revit version: Autodesk Revit 2022 (Build: 20220123_1515(x64))

	C:\Users\...\Documents\Revit_temp\Project1_collab.rvt
	File exists: YES
	File size: 65.89MB
	Revit version: Autodesk Revit 2024 (Build: 20230911_1230(x64))

16/02/2024 10:05:14 : 
16/02/2024 10:05:14 : Starting batch operation...
16/02/2024 10:05:14 : 
16/02/2024 10:05:14 : Processing Revit file (1 of 2) in Revit 2022 session.
16/02/2024 10:05:14 : 
	V:\PROJECT DATA\2021\...S22.rvt
	File exists: YES
	File size: 55.57MB
	Revit version: Autodesk Revit 2022 (Build: 20220123_1515(x64))

16/02/2024 10:05:14 : 
16/02/2024 10:05:14 : Starting Revit 2022 session...
16/02/2024 10:05:14 : 
16/02/2024 10:05:14 : Monitoring host Revit process (PID: 22216)
16/02/2024 10:05:14 : 
16/02/2024 10:06:08 : 	- 
16/02/2024 10:06:08 : 	- Processing file (1 of 2): V:\PROJECT DATA\2021\...S22.rvt
16/02/2024 10:06:08 : 	- 
16/02/2024 10:06:08 : 	- The file is a Central Model file.
16/02/2024 10:06:08 : 	- 
16/02/2024 10:06:08 : 	- Operation aborted.
16/02/2024 10:06:08 : 	- 
16/02/2024 10:06:08 : 	- ERROR: An error occurred while processing the file!
16/02/2024 10:06:08 : 	- 
16/02/2024 10:06:08 : 	- Exception: [AttributeError] 'type' object has no attribute 'GetRevitLocalFilePath'
16/02/2024 10:06:08 : 	- .NET exception: [MissingMemberException] 'type' object has no attribute 'GetRevitLocalFilePath'
16/02/2024 10:06:08 : 	- 
16/02/2024 10:06:08 : 	- Further exception information:
16/02/2024 10:06:08 : 	- 
16/02/2024 10:06:08 : 	- 	RunBatchTaskScript$63: 1450: [250-250] 'C:\Users\...\Downloads\RevitBatchProcessor-master\RevitBatchProcessor-master\BatchRvtGUI\bin\x64\Debug\Scripts\revit_script_host.py'
16/02/2024 10:06:08 : 	- 	<lambda$3>$62: 30: [384-384] 'C:\Users\...\Downloads\RevitBatchProcessor-master\RevitBatchProcessor-master\BatchRvtGUI\bin\x64\Debug\Scripts\revit_script_host.py'
16/02/2024 10:06:08 : 	- 	WithErrorHandling$25: 89: [49-49] 'C:\Users\...\Downloads\RevitBatchProcessor-master\RevitBatchProcessor-master\BatchRvtGUI\bin\x64\Debug\Scripts\script_host_error.py'
16/02/2024 10:06:08 : 	- 	DoRevitSessionProcessing$46: 316: [383-388] 'C:\Users\...\Downloads\RevitBatchProcessor-master\RevitBatchProcessor-master\BatchRvtGUI\bin\x64\Debug\Scripts\revit_script_host.py'
16/02/2024 10:06:08 : 	- 	<lambda$4>$45: 36: [419-425] 'C:\Users\...\Downloads\RevitBatchProcessor-master\RevitBatchProcessor-master\BatchRvtGUI\bin\x64\Debug\Scripts\revit_script_host.py'
16/02/2024 10:06:08 : 	- 	WithErrorHandling$25: 89: [49-49] 'C:\Users\...\Downloads\RevitBatchProcessor-master\RevitBatchProcessor-master\BatchRvtGUI\bin\x64\Debug\Scripts\script_host_error.py'
16/02/2024 10:06:08 : 	- 	outputStreamWriterAction$42: 66: [418-429] 'C:\Users\...\Downloads\RevitBatchProcessor-master\RevitBatchProcessor-master\BatchRvtGUI\bin\x64\Debug\Scripts\revit_script_host.py'
16/02/2024 10:06:08 : 	- 	UsingStream$39: 61: [84-84] 'C:\Users\...\Downloads\RevitBatchProcessor-master\RevitBatchProcessor-master\BatchRvtGUI\bin\x64\Debug\Scripts\stream_io_util.py'
16/02/2024 10:06:08 : 	- 	outputStreamAction$40: 73: [432-432] 'C:\Users\...\Downloads\RevitBatchProcessor-master\RevitBatchProcessor-master\BatchRvtGUI\bin\x64\Debug\Scripts\revit_script_host.py'
16/02/2024 10:06:08 : 	- 	UsingStream$39: 61: [84-84] 'C:\Users\...\Downloads\RevitBatchProcessor-master\RevitBatchProcessor-master\BatchRvtGUI\bin\x64\Debug\Scripts\stream_io_util.py'
16/02/2024 10:06:08 : 	- 	Main$26: 205: [435-435] 'C:\Users\...\Downloads\RevitBatchProcessor-master\RevitBatchProcessor-master\BatchRvtGUI\bin\x64\Debug\Scripts\revit_script_host.py'
16/02/2024 10:06:08 : 	- 	WithErrorHandling$25: 89: [49-49] 'C:\Users\...\Downloads\RevitBatchProcessor-master\RevitBatchProcessor-master\BatchRvtGUI\bin\x64\Debug\Scripts\script_host_error.py'
16/02/2024 10:06:08 : 	- 	<unnamed>: 451: [447-451] 'C:\Users\...\Downloads\RevitBatchProcessor-master\RevitBatchProcessor-master\BatchRvtGUI\bin\x64\Debug\Scripts\revit_script_host.py'
16/02/2024 10:06:22 : 
16/02/2024 10:06:22 : Revit process (PID: 22216) has exited!
16/02/2024 10:06:22 : 
16/02/2024 10:06:22 : Processing Revit file (2 of 2) in Revit 2024 session.
16/02/2024 10:06:22 : 
	C:\Users\...\Documents\Revit_temp\Project1_collab.rvt
	File exists: YES
	File size: 65.89MB
	Revit version: Autodesk Revit 2024 (Build: 20230911_1230(x64))

16/02/2024 10:06:22 : 
16/02/2024 10:06:22 : Starting Revit 2024 session...
16/02/2024 10:06:22 : 
16/02/2024 10:06:22 : Monitoring host Revit process (PID: 20556)
16/02/2024 10:06:22 : 
16/02/2024 10:07:05 : 	- 
16/02/2024 10:07:06 : 	- Processing file (2 of 2): C:\Users\...\Documents\Revit_temp\Project1_collab.rvt
16/02/2024 10:07:06 : 	- 
16/02/2024 10:07:06 : 	- The file is a Central Model file.
16/02/2024 10:07:06 : 	- 
16/02/2024 10:07:06 : 	- Operation aborted.
16/02/2024 10:07:06 : 	- 
16/02/2024 10:07:06 : 	- ERROR: An error occurred while processing the file!
16/02/2024 10:07:06 : 	- 
16/02/2024 10:07:06 : 	- Exception: [AttributeError] 'type' object has no attribute 'GetRevitLocalFilePath'
16/02/2024 10:07:06 : 	- .NET exception: [MissingMemberException] 'type' object has no attribute 'GetRevitLocalFilePath'
16/02/2024 10:07:06 : 	- 
16/02/2024 10:07:06 : 	- Further exception information:
16/02/2024 10:07:06 : 	- 
16/02/2024 10:07:06 : 	- 	RunBatchTaskScript$63: 1450: [250-250] 'C:\Users\...\Downloads\RevitBatchProcessor-master\RevitBatchProcessor-master\BatchRvtGUI\bin\x64\Debug\Scripts\revit_script_host.py'
16/02/2024 10:07:06 : 	- 	<lambda$3>$62: 30: [384-384] 'C:\Users\...\Downloads\RevitBatchProcessor-master\RevitBatchProcessor-master\BatchRvtGUI\bin\x64\Debug\Scripts\revit_script_host.py'
16/02/2024 10:07:06 : 	- 	WithErrorHandling$25: 89: [49-49] 'C:\Users\...\Downloads\RevitBatchProcessor-master\RevitBatchProcessor-master\BatchRvtGUI\bin\x64\Debug\Scripts\script_host_error.py'
16/02/2024 10:07:06 : 	- 	DoRevitSessionProcessing$46: 316: [383-388] 'C:\Users\...\Downloads\RevitBatchProcessor-master\RevitBatchProcessor-master\BatchRvtGUI\bin\x64\Debug\Scripts\revit_script_host.py'
16/02/2024 10:07:06 : 	- 	<lambda$4>$45: 36: [419-425] 'C:\Users\...\Downloads\RevitBatchProcessor-master\RevitBatchProcessor-master\BatchRvtGUI\bin\x64\Debug\Scripts\revit_script_host.py'
16/02/2024 10:07:06 : 	- 	WithErrorHandling$25: 89: [49-49] 'C:\Users\...\Downloads\RevitBatchProcessor-master\RevitBatchProcessor-master\BatchRvtGUI\bin\x64\Debug\Scripts\script_host_error.py'
16/02/2024 10:07:06 : 	- 	outputStreamWriterAction$42: 66: [418-429] 'C:\Users\...\Downloads\RevitBatchProcessor-master\RevitBatchProcessor-master\BatchRvtGUI\bin\x64\Debug\Scripts\revit_script_host.py'
16/02/2024 10:07:06 : 	- 	UsingStream$39: 61: [84-84] 'C:\Users\...\Downloads\RevitBatchProcessor-master\RevitBatchProcessor-master\BatchRvtGUI\bin\x64\Debug\Scripts\stream_io_util.py'
16/02/2024 10:07:06 : 	- 	outputStreamAction$40: 73: [432-432] 'C:\Users\...\Downloads\RevitBatchProcessor-master\RevitBatchProcessor-master\BatchRvtGUI\bin\x64\Debug\Scripts\revit_script_host.py'
16/02/2024 10:07:06 : 	- 	UsingStream$39: 61: [84-84] 'C:\Users\...\Downloads\RevitBatchProcessor-master\RevitBatchProcessor-master\BatchRvtGUI\bin\x64\Debug\Scripts\stream_io_util.py'
16/02/2024 10:07:06 : 	- 	Main$26: 205: [435-435] 'C:\Users\...\Downloads\RevitBatchProcessor-master\RevitBatchProcessor-master\BatchRvtGUI\bin\x64\Debug\Scripts\revit_script_host.py'
16/02/2024 10:07:06 : 	- 	WithErrorHandling$25: 89: [49-49] 'C:\Users\...\Downloads\RevitBatchProcessor-master\RevitBatchProcessor-master\BatchRvtGUI\bin\x64\Debug\Scripts\script_host_error.py'
16/02/2024 10:07:06 : 	- 	<unnamed>: 451: [447-451] 'C:\Users\...\Downloads\RevitBatchProcessor-master\RevitBatchProcessor-master\BatchRvtGUI\bin\x64\Debug\Scripts\revit_script_host.py'
16/02/2024 10:07:16 : 
16/02/2024 10:07:16 : Revit process (PID: 20556) has exited!
16/02/2024 10:07:16 : 
16/02/2024 10:07:16 : Operation completed.

**Comment by petersmithfromengland** [comment]
Maciej's update was incorporated in [version 1.10-beta](https://github.com/bvn-architecture/RevitBatchProcessor/releases/tag/v1.10.0-beta)
