### ISSUE TITLE
Feature Request - Run at scheduled interval

### ISSUE THREAD

**Issue by baaswietse** [bvn-architecture/RevitBatchProcessor#120]
Hello,
Would it be possible to make the batch processor run at a scheduled interval? E.g. daily at 2 AM.

**Comment by maciejwypych** [comment]
You can use Windows Task Scheduler to run it. Create a task with RBP in
command line mode

**Comment by moinnagani1** [comment]
Is there a way to keep a previously opened file keep open in Revit? I want to compile a list of files and then initiate a batch process that will open these files in multiple instances of Revit. Once a Revit file is opened, it should remain open and not close. Is this or something similar possible?

**Comment by notionparallax** [comment]
@moinnagani1 this feels like a new issue. Is it? Or is it related to running jobs on a schedule?
If it's a new issue, it would be better to open a new issue so it can get the attention it deserves.

**Comment by notionparallax** [comment]
@maciejwypych this seems like a good thing to add to the [FAQ](https://github.com/bvn-architecture/RevitBatchProcessor/wiki/Revit-Batch-Processor-FAQ)s. What do you think?
