### ISSUE TITLE
Workaround "You are trying to checkout a large number of elements..."

### ISSUE THREAD

**Issue by hkbr** [bvn-architecture/RevitBatchProcessor#123]
RBP does seem to be able to handle the warning 'You are trying to checkout a large number of elements. Instead checkout the following worksets <...>', when for instance updating a parameter value of several elements in a workshared model.

Does anyone know a workaround to this issue? is there a way to set up a dynamo script to avoid this warning all together?

Thanks!

Håkon

**Comment by jchristel** [comment]
Hi Hakon,

Just to confirm: are you saying RBP is handling the warning ok, or is it stopping processing a file when that warning occurs? I cant quite tell from your message whether you are flagging an issue with RBP or just wanting to find out how RBP does handle warnings.

Kind regards,
Jan

**Comment by hkbr** [comment]
Thanks so much for the reply, and sorry for the vagueness. The meaning of the post was the latter, RBP stopping at the error.

However;
This was once again my bad - the error that was actually responsible for stopping the process was the 'cannot edit elements in group'. Worked around this by exporting the group Id's, and skipping elements in those groups in the script. Not a perfect solution, but good enough.
