### ISSUE TITLE
Export log file 

### ISSUE THREAD

**Issue by walid-el** [bvn-architecture/RevitBatchProcessor#18]
@DanRumery it would very useful to export log file, and is there a anyway to have a option that handles revit dialog box with yes or no ?

**Comment by DanRumery** [comment]
@walid-el Actually RBP does export a log file, by default it is written to `%LOCALAPPDATA%\BatchRvt\BatchRvt_XXXXXXXXXX.log` (where XXXXXXXXXX is the timestamp at the start of processing)

This log file is in json format, however, so it is not so easy to read. So I agree there should be an option to export a readable log file. I'll consider it for the next release.

**Comment by DanRumery** [comment]
@walid-el I've moved the second question to a new issue (re dialog box yes/no option)

**Comment by DanRumery** [comment]
The next release (a couple of days away) will save a plain-text copy of the log file and will also note this in the output at the end of processing.

**Comment by DanRumery** [comment]
Add in v1.4.4 (https://github.com/bvn-architecture/RevitBatchProcessor/releases/tag/v1.4.4)
