### ISSUE TITLE
please add revit 2019 

### ISSUE THREAD

**Issue by ErwinMeulman** [bvn-architecture/RevitBatchProcessor#20]

**Comment by ErwinMeulman** [comment]
thanks Dan

**Comment by DanRumery** [comment]
@ErwinMeulman

Hi Erwin, I've now updated RBP for Revit 2019 support (although of course you will need 2019 installed).

Please see here:

https://github.com/bvn-architecture/RevitBatchProcessor/releases/tag/v1.4

And let me know if you encounter any issues in 2019. I've done a lot of testing however I don't yet have a lot of Revit 2019 files to test with so I'd appreciate any feedback!

Regards
