### ISSUE TITLE
BatchRvt Error R2018 - Could not add references to assembly BatchRvtUtil

### ISSUE THREAD

**Issue by HAO-BSM** [bvn-architecture/RevitBatchProcessor#26]
Fails on opening project, see error/setting details below:

Error Message: System.IO.IOException: Could not add reference to assembly BatchRvtUtil

**Error Pop Up**
![image](https://user-images.githubusercontent.com/45675300/51887646-a50d2e00-23e8-11e9-8b3a-dac54f3619f7.png)

**Export Settings**
![image](https://user-images.githubusercontent.com/45675300/51887594-8444d880-23e8-11e9-8203-62b29c4eda67.png)

Your help/suggestion is greatly appreciated.  
Cheers, 
Tom

**Comment by HAO-BSM** [comment]
Uninstalled PyRevit 4.6.11 and it successfully to processed dynamo task script. However it still showed error message. 
![image](https://user-images.githubusercontent.com/45675300/51945902-1a721080-2474-11e9-8906-f3e2b1a19c01.png)

**Comment by DanRumery** [comment]
@HAO-BSM Thanks for reporting this!  I'll investigate why RBP and PyRevit aren't playing nicely. My guess is that I'm using an older version of IronPython that isn't compatible with PyRevit's. I'll get back to you on this.

As for the `[REVIT ERROR MESSAGE]' messages these particular ones can be ignored. They seem to be generated from some other addin but they shouldn't affect RBP's operation. The reason that I make RBP show such messages is that sometimes they are important Revit errors but there isn't a way to know which ones are truly errors or not. (It's basically reading from the internal Revit application's standard error stream.)

**Comment by HAO-BSM** [comment]
Thanks @DanRumery, great work on the program too!

**Comment by DanRumery** [comment]
So I've narrowed it down to a difference in IronPython behaviour when PyRevit is present versus when it is not.

For whatever reason `clr.AddReference("BatchRvtUtil")` is not adding the reference despite the path of the assembly existing already in `sys.path`. Instead if I use `clr.AddReferenceToFileAndPath("[path to assembly]\BatchRvtUtil")` then it seems to work even with PyRevit present. I'm still not sure why this is only an issue when PyRevit is installed. I even experimented with PyRevit's IronPython version setting but that didn't seem to fix the problem. A mystery...

Anyway I'll upload a new pre-release with the fix in a day or two...

**Comment by DanRumery** [comment]
@HAO-BSM 

Please install pre-release v1.4.4: https://github.com/bvn-architecture/RevitBatchProcessor/releases/tag/v1.4.4

This update should fix the problem. Please let me know if you still have issues with PyRevit installed!

**Comment by HAO-BSM** [comment]
Awesome, thanks @DanRumery.  

It works a treat! Now using latest PyRevit v4.6.15 and no issues.

**Comment by DanRumery** [comment]
Great! :+1:
