### ISSUE TITLE
RBP fails if file is already open

### ISSUE THREAD

**Issue by RyanSchw** [bvn-architecture/RevitBatchProcessor#45]
If a Revit instance is already open (not through RBP) with one of the files in the list, RBP is not able to find the Revit Version.

```
13:41:08 : Reading Revit File list:
13:41:08 : 
13:41:08 : 	C:\Users\xxx\Desktop\list.csv
13:41:08 : 
13:41:08 : WARNING: The following Revit Files are of an unsupported version (1):
13:41:08 : 
13:41:08 : 	xxx\Multiple_Doors.rvt
13:41:08 : 	File exists: YES
13:41:08 : 	File size: 55.65MB
13:41:08 : 	Revit version: NOT DETECTED!
13:41:08 : 
13:41:08 : ERROR: All specified Revit Files are of an unsupported version or have an unsupported file path.
13:41:08 : 
13:41:08 : Operation aborted.
```

Normally when the same file is opened twice on different Revit instances (same computer), a dialog box will pop up saying
![image](https://user-images.githubusercontent.com/32225075/64129102-0c78cb00-cd88-11e9-8534-d34121c82bcb.png)

I would say it's a separate issue if the file should actually be processed or not (if the script asks to save the file, that wouldn't be possible since it's read only) -- but regardless the error message for this specific case should be more specific. The script didn't fail because it couldn't find the Revit verison, it failed because the Revit file is already open.

Side note: I can have the same version Revit open (with a different file open) with no issue -- this is only the case if one of the listed files is already open in Revit.

**Comment by RyanSchw** [comment]
Also, this was tested on commit 20e0ff1d6fd6cf08064869491e9e4ec3c6fe0d8d so that it would not be affected by #43

**Comment by DanRumery** [comment]
Yep it has something to do with how I'm reading the version information---it's opening the file with shared Read permissions which would normally do the trick but perhaps it requires shared ReadWrite permissions. Will have a play...

**Comment by RyanSchw** [comment]
Doesn't necessarily have to be fixed, primarily just wanted to log it as a known issue here for people that are having problems.

**Comment by DanRumery** [comment]
@RyanSchw good point. I'll add something to the FAQ.
