### ISSUE TITLE
run vb.net dll instead of c# dll

### ISSUE THREAD

**Issue by rayray4105** [bvn-architecture/RevitBatchProcessor#47]
Hi,

Is there a way to run vb.net dll instead of c# dll? I have some routines in different coding and I would like to run them both. 

regards,
Raymond

**Comment by RyanSchw** [comment]
I found a quick tutorial on [how to call a vb.net function from IronPython](http://opensimulator.org/git/opensim-libs-save/IronPython/IronPython-1.1.1/Tutorial/Tutorial.htm#T5.2). This tutorial is for IronPython 1.1.1 (we're running 2.7.x?), but the idea should be the same.

As far as I can see, you should be able to use the [same method to execute as C#](https://github.com/bvn-architecture/RevitBatchProcessor#executing-functions-in-a-c-dll
) using the `.dll` import.

**Comment by rayray4105** [comment]
You are absolutely right. Running VB code now works. 

`clr.AddReferenceToFile("AutorunTestDLL.dll")
from AutorunTestDLL import Autorun

Autorun.AutorunTestShared(doc,uiapp)`

Passing arguments also possible when using a 'public shared sub' or 'public shared function'

**Comment by RyanSchw** [comment]
Thanks for the info and I'm glad you got it working!

I'll go ahead and add your comments to the documentation.

btw, you can do block code comments by doing ` ``` ` at the [top and bottom](https://guides.github.com/features/mastering-markdown/) (single ` is just for single line)

**Comment by rayray4105** [comment]
Thanks for the tip ;)
