### ISSUE TITLE
Does RevitBatchProcessor run Revit Server based models ?

### ISSUE THREAD

**Issue by rayray4105** [bvn-architecture/RevitBatchProcessor#48]
Hi,

Cab RevitBatchProcessor run Revit Server based models? 

We are using Revit Server to be able to open the central models on two different office locations. I would like to open and detach from Revit server before starting any operations instead of the local copy of the worksharing model.

Thanks for your effort!

**Comment by RyanSchw** [comment]
I’m not entirely sure of how the file structure is set up with Revit Server, but I may be able to offer some insight. 

It is possible to open a ‘.rvt’ file on a network drive like ‘\\fsmydata\data\Vol5 ...etc’. [This](https://forums.autodesk.com/t5/revit-architecture-forum/revit-file-location-issues-versus-network-server-location/m-p/7149819#M152718) might be a related issue. If you have a network drive like ‘P:\\‘ that’s mapped to ‘\\fsmydata\’, use ‘\\fsmydata’.

**Comment by DanRumery** [comment]
I don't think it will work but you could try prefixing with the address of the Revit server (from memory Revit Server addresses start with RSN:// I think?)

**Comment by DanRumery** [comment]
For reference:

https://thebuildingcoder.typepad.com/blog/2014/08/accessing-a-revit-server-central-model-path.html

**Comment by rayray4105** [comment]
Already thried that but unfortunately no go.

**Comment by Zet-Cher** [comment]
Please, let me know if you find a solution to the problem.

**Comment by htlcnn** [comment]
Could you set up a VPN, then access central model just like you're working on LAN?

**Comment by DanRumery** [comment]
There won't be any support for Revit Server. But there is limited support for BIM360 models coming soon.

**Comment by ifan168** [comment]
I've forked RevitBatchProcessor and added support for Revit RSN. You might want to give it a try.
