### ISSUE TITLE
Does RevitBatchProcessor run the revit journal file ?

### ISSUE THREAD

**Issue by yourpapar** [bvn-architecture/RevitBatchProcessor#53]
I need to do some complicated operations on Revit. I want to do it manually, then find the journal txt generated by revit, and then run the journal txt on your revitBatchProcessor to batch process the model files to achieve the same model processing

**Comment by DanRumery** [comment]
Hi @yourpapar 

RBP doesn't use the journal file approach but rather uses the Windows and Revit API to automate the work. So unfortunately what you want to do is not possible with RBP.

Revit journal files are very context-sensitive and cannot interact with the Revit API so they're not very useful for reliable automation of Revit files.

It would be great if Revit had some sort of macro recorder that generated code equivalent to the actions performed but sadly even the Revit API doesn't cover the full scope of actions that Revit can perform.

**Comment by DanRumery** [comment]
Closing this as it's not possible to mix the running of journal file actions with RBP script automation.
