### ISSUE TITLE
Launch external addin command in python script doesn't work

### ISSUE THREAD

**Issue by bugrunnerzhang** [bvn-architecture/RevitBatchProcessor#54]
I have a released revit addin, it could write some meta-info about rvt into external file. This addin also expose external command interface. According to the method of this link[https://thebuildingcoder.typepad.com/blog/2013/10/programmatic-custom-add-in-external-command-launch.html], I can successfully call this addin through PostCommand in C#, but after I port it into the python script, it cannot be called successfully. Is the method I used wrong? Or is the location of the call inappropriate?
![image](https://user-images.githubusercontent.com/3183283/73524494-33771e00-4448-11ea-8e7d-02c178e37370.png)

**Comment by bugrunnerzhang** [comment]
@DanRumery After some tests I found the reason, Revit will exit after the python script task execution is completed, so the command message sent to revit can not be executed, I have solved this by other means. 
Thank you for sharing this useful project!

**Comment by DanRumery** [comment]
Ah yes those postable commands only execute after the addin command executes so RBP isn't compatible with that mechanism. If it's your own addin you're invoking then you could just add the module as a reference and call one of its functions directly. See the FAQ about calling functions written in a C# module.
