### ISSUE TITLE
RevitBtchAddin not showing in Revit 2019 after Installation

### ISSUE THREAD

**Issue by craigpatson** [bvn-architecture/RevitBatchProcessor#55]
Hi @DanRumery 

I can't find RevitBatchAddin in my Revit 2019 after installing Installer for Revit Batch Processor v1.5.3.
Is it because i have 2 dynamo version 1.3.4 and 2.0.3?
Could you please assist on this.

Thanks & Best Regards,

**Comment by DanRumery** [comment]
Hi @craigpatson 
Although RBP won't work with two Dynamo versions installed, it shouldn't cause the addin itself to be missing. When you say you can't find the addin do you mean that RBP doesn't allow you to select 2019 in the version selection dropdown? Or that the addin files themselves don't exist at all? 

- Can you tell me what what your Revit 2019 installation path is?
- Also can you confirm whether the file `BatchRvtAddin2019.addin` exists under:
`C:\Users\<username>\AppData\Roaming\Autodesk\Revit\Addins\2019`

**Comment by craigpatson** [comment]
Hi @DanRumery 

Thanks for replying. My revit 2019 installation path is C:\Program Files\Autodesk\Revit 2019 and BatchRvtAddin2019.addin exists under C:\..AppData\Roaming\Autodesk\Revit\Addins\2019
![image](https://user-images.githubusercontent.com/60637390/74079173-23b19800-4a4d-11ea-9854-a0b0c4a57cee.png)
I can find RBP in Start->Programs but not in Revit 2019 as addin. May be it is only exist in Programs not as Revit addin?
![image](https://user-images.githubusercontent.com/60637390/74079239-ebf72000-4a4d-11ea-9358-97e0be65439b.png)

**Comment by DanRumery** [comment]
@craigpatson That's correct. You have to use that program in the start menu to run RBP. RBP manages the Revit sessions itself so you don't need to start Revit, you just open Revit Batch Processor and setup the program from there.

**Comment by DanRumery** [comment]
Closing this assuming you found RBP in the start menu.
