### ISSUE TITLE
CLI argument: path format

### ISSUE THREAD

**Issue by jbenoit44** [bvn-architecture/RevitBatchProcessor#56]
Hi, thank you for the excellent work here.
I have an issue with using CLI commands: I feed a path as an argument, but Batchrvt.exe returns an error "the given path format is not supported" or similar. it just goes too fast so I can really read it.

Path is something like: "‪C:\Users\Julien\Dropbox\10-XXXXXXX\BatchRvt.Settings.json"
I did this because the json file for settings is not in the Default location.
when I use the default, it works great. any clue?

**Comment by jbenoit44** [comment]
might be related: I can't get the scheduler to run the task. from log file:

{"msgId":"","message":"ERROR: No settings file specified or settings file not found."}}

**Comment by jbenoit44** [comment]
ok, Scheduler is fine when you specify the entire path, json file being in the same folder than the EXE.

**Comment by DanRumery** [comment]
Hi @jbenoit44

Can you show me the full command-line you're using to run BatchRvt.exe? Does the same error happen when you open a command prompt in the RevitBatchProcessor folder and run the executable command-line from there too? Or does it only happen when running from the Task Scheduler?

I suspect if it works from the command-line then it has something to do with the working directory of the task. Can you export the scheduled task settings to xml and post that here too?

**Comment by DanRumery** [comment]
Also just to confirm, you say Revit is crashing only when run on the timer from the task scheduler and not when run manually? That is very odd indeed. I'm wondering how to replicate that scenario...

**Comment by jbenoit44** [comment]
I tested more, and figured that it crashes only when the option "user is logged in or not" is checked. So must be WTS related. Also, it appears that the path to my dropbox folder is messing things here. No issue with regular folder. 
Last, in WTS, the argument doesn't need "" for the files path.
I will continue testing, mostly with more complex dynamo definition, and will probably publish a blog post, I love your stuff, brilliant!
Cheers.

**Comment by DanRumery** [comment]
@jbenoit44 Ah yes! That would explain it. Those user paths would be off-limits for non-logon tasks. Also possibly the Windows UI subsystem isn't initialized in that scenario too.

**Comment by DanRumery** [comment]
Also thanks for the praise :)

will keep an eye out for your blog post!
