### ISSUE TITLE
Revit under proxy enviornment

### ISSUE THREAD

**Issue by kanicrab** [bvn-architecture/RevitBatchProcessor#57]
I can start revit under proxy settings without problem, but when I start with RevitBatchProcessor I received errors below : 

seems those proxy settings cannot pass through and my account was locked afterthat

10:48:27 :      - [ REVIT ERROR MESSAGE ] : [0304/104824.964:VERBOSE1:pref_proxy_config_tracker_impl.cc(151)] 00000000550B9E00: set chrome proxy config service to 00000000550BA120
10:48:27 :      - [ REVIT ERROR MESSAGE ] : [0304/104824.964:VERBOSE1:pref_proxy_config_tracker_impl.cc(278)] 00000000550B9E00: Done pushing proxy to UpdateProxyConfig
10:48:27 :      - [ REVIT ERROR MESSAGE ] : [0304/104824.965:VERBOSE1:multi_log_ct_verifier.cc(75)] Adding CT log: Google 'Pilot' log
10:48:27 :      - [ REVIT ERROR MESSAGE ] : [0304/104824.965:VERBOSE1:multi_log_ct_verifier.cc(75)] Adding CT log: Google 'Aviator' log
10:48:27 :      - [ REVIT ERROR MESSAGE ] : [0304/104824.965:VERBOSE1:multi_log_ct_verifier.cc(75)] Adding CT log: DigiCert Log Server
10:48:27 :      - [ REVIT ERROR MESSAGE ] : [0304/104824.965:VERBOSE1:multi_log_ct_verifier.cc(75)] Adding CT log: Google 'Rocketeer' log
10:48:27 :      - [ REVIT ERROR MESSAGE ] : [0304/104824.965:VERBOSE1:multi_log_ct_verifier.cc(75)] Adding CT log: Symantec log
10:48:27 :      - [ REVIT ERROR MESSAGE ] : [0304/104824.965:VERBOSE1:multi_log_ct_verifier.cc(75)] Adding CT log: Venafi log
10:48:27 :      - [ REVIT ERROR MESSAGE ] : [0304/104824.965:VERBOSE1:multi_log_ct_verifier.cc(75)] Adding CT log: Symantec 'Vega' log
10:48:27 :      - [ REVIT ERROR MESSAGE ] : [0304/104824.966:VERBOSE1:multi_log_ct_verifier.cc(75)] Adding CT log: CNNIC CT log
10:48:27 :      - [ REVIT ERROR MESSAGE ] : [0304/104824.966:VERBOSE1:multi_log_ct_verifier.cc(75)] Adding CT log: WoSign log
10:48:27 :      - [ REVIT ERROR MESSAGE ] : [0304/104824.966:VERBOSE1:multi_log_ct_verifier.cc(75)] Adding CT log: StartCom CT log
10:48:27 :      - [ REVIT ERROR MESSAGE ] : [0304/104824.966:VERBOSE1:multi_log_ct_verifier.cc(75)] Adding CT log: Google 'Skydiver' log
10:48:27 :      - [ REVIT ERROR MESSAGE ] : [0304/104824.966:VERBOSE1:multi_log_ct_verifier.cc(75)] Adding CT log: Google 'Icarus' log
10:48:27 :      - [ REVIT ERROR MESSAGE ] : [0304/104824.966:VERBOSE1:multi_log_ct_verifier.cc(75)] Adding CT log: Izenpe log
10:48:27 :      - [ REVIT ERROR MESSAGE ] : [0304/104824.966:VERBOSE1:multi_log_ct_verifier.cc(75)] Adding CT log: Certly.IO log

**Comment by DanRumery** [comment]
Hi @kanicrab 

Is there more to the log file error messages than this? The reason I ask is that those particular error messages are coming from either Revit itself or another addin. They're not related to RBP but RBP reports those log messages for troubleshooting purposes. Is Revit crashing on startup from RBP? Can you post the full log file (with sensitive details removed)?

**Comment by kanicrab** [comment]
Hi Dan,

Thank you for your reply.

I found that windows system parameters http_proxy and https_proxy will
cause this message for your information.
You are right, that is revit message but it just did not explain it is from
revit itself, plugins or python attempt.

Dan Rumery <notifications@github.com> 於 2020年3月5日 週四 上午10:18寫道：
