### ISSUE TITLE
Option for Revit session time-out so that a hung Revit process doesn't block further processing.

### ISSUE THREAD

**Issue by DanRumery** [bvn-architecture/RevitBatchProcessor#6]

**Comment by Amehr** [comment]
@DanRumery It would be great if the processor jumps to the next file path if a model/file path doesn't exist

**Comment by DanRumery** [comment]
Ideally if the process is terminated as a result of the time-out, then the remaining files (including those that would have been processed within the same session had it not timed-out) should be processed in a fresh Revti session(s).

**Comment by DanRumery** [comment]
Added in RBP v1.2.8!

See v1.2.8 release notes:

https://github.com/bvn-architecture/RevitBatchProcessor/releases/tag/v1.2.8
