### ISSUE TITLE
Dynamo Script Run Completed but opening Revit doesn't show the results

### ISSUE THREAD

**Issue by sajjad1983** [bvn-architecture/RevitBatchProcessor#63]
Hi @DanRumery 

Hope you're doing well. Today i downloaded RevitBatchProcessor tool and tried to run dynamo script. At the end of the operation it says "Operation Completed" but when i open revit file it is the same as previous no change in the revit file. Could you please help me with this. Here is the image at the end of the log:
![image](https://user-images.githubusercontent.com/67874541/86539861-0952ec00-bf11-11ea-8e3b-9e84419f3a06.png)

**Comment by sajjad1983** [comment]
Hi @DanRumery ,

Could you please help me on this.

**Comment by DanRumery** [comment]
@sajjad1983 Hi there, if you add a Save / Sync node to your Dynamo script it should no longer show that message. There are a couple of packages that have such nodes (I believe Orchid is one of them).

Let me know if that works...

**Comment by DanRumery** [comment]
There's a mention in the Wiki/FAQ about that just in case people aren't aware of the behaviour.

**Comment by sajjad1983** [comment]
Thanks a lot @DanRumery  works like a charm. One more thing why same **Revit Version** greyed out. How can i use this functionality. 
![image](https://user-images.githubusercontent.com/67874541/86774585-bb043100-c067-11ea-843f-921d45218f0f.png)

**Comment by DanRumery** [comment]
@sajjad1983 it's disabled for Dynamo task scripts because I wasn't able to figure out how to reset the Dynamo engine within a single Revit session. The option is only enabled for Python task scripts as a result.

**Comment by sajjad1983** [comment]
That does makes sense. Thanks a lot. Have a nice day :)

**Comment by DanRumery** [comment]
Thanks you're welcome! same you too :)
