### ISSUE TITLE
Cloud model issue during save/synchronising

### ISSUE THREAD

**Issue by punderscoresmithuk** [bvn-architecture/RevitBatchProcessor#66]
Hi Dan,

As previously chatted about, been receiving ".NET exception: [InvalidOperationException] This Document has an open editing transaction and is accepting changes." when working with cloud models and perform a task script over them.

Upon further digging and investigation it's occurring when trying to save or synchronise the model back to the central. The above exception is thrown. If I remove the save/sync step I receive an error that the model could not have been closed because of a transaction being open. 

Task script:
```
import clr
import System
clr.AddReference("System.Core")
clr.ImportExtensions(System.Linq)

clr.AddReference("RevitAPI")
clr.AddReference("RevitAPIUI")
from Autodesk.Revit.DB import *

clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

import revit_script_util
from revit_script_util import Output
import revit_file_util
from revit_file_util import SynchronizeWithCentral

sessionId = revit_script_util.GetSessionId()
uiapp = revit_script_util.GetUIApplication()
app = uiapp.Application

#retrieving the document only makes sense when running in batch Revit file processing mode.
doc = revit_script_util.GetScriptDocument()

TransactionManager.Instance.EnsureInTransaction(doc)

projInfo = doc.ProjectInformation
projNameParam = projInfo.get_Parameter(BuiltInParameter.PROJECT_NAME)
projNameParam.Set('Different to what was before')

TransactionManager.Instance.TransactionTaskDone()

Output()
Output("Project Name changed to: "+ projNameParam.AsString())
Output()

revit_file_util.SynchronizeWithCentral(doc,"Changed Project Name")
```

Console log below, can provide the full .txt file if thats helpful

![image](https://user-images.githubusercontent.com/51383696/91924664-71625a80-ed27-11ea-9d80-2a8a15d773fc.png)

Let me know if you need any further info

Cheers, Pete

**Comment by DanRumery** [comment]
For others reading, we eventually found the issue was related to the use of Dynamo's RevitServices module to manage transactions (TransactionManager). The python task script must use the Revit API Transaction class only as the Dynamo modules aren't compatible with python running outside of the Dynamo environment.

**Comment by punderscoresmithuk** [comment]
Thanks again Dan
