### ISSUE TITLE
Batch upgrading of Revit projects and family files instruction

### ISSUE THREAD

**Issue by guysoft** [bvn-architecture/RevitBatchProcessor#69]
Hey all, 
In the feature list there is an entry:
"Batch upgrading of Revit projects and family files"

How would I do that? When I try and open anything there is an error message that I need a dynamo or python script.

Could it be possible to explain how would I do that using this tool?
Better yet - would happy to help and add that to the FAQ once I understand how it is done.

**Comment by DanRumery** [comment]
Hi @guysoft 

Sorry for the delayed response!

The batch upgrading idea is listed under "use cases" as a motivation for why batch processing can be useful. I don't have access to Revit these days, however the gist of how to do this is to choose the specific version of Revit that you want to upgrade your files to, generate the file list of the source files to upgrade, make a basic Dynamo or python script that does a SaveAs operation for a given file (e.g. using Dynamo / Revit API to extract the current filename, combine the new folder path and filename for where to save the upgraded file, and pass this to a SaveAs node / code.) RBP is fairly good at automatically handling any warnings that may arise during upgrading (which might happen as the file is opened in the specific Revit version you chose in the RBP dialog, assuming the Revit version is newer than the file version).

**Comment by guysoft** [comment]
Hey, 
I figured how to do that strangely enough today!

Attaching below for future people.
I am now stuck with lots of C# code in an addin I wrote that I want to incoperate to this open->upgrade->save script.
So I might ask you about that later on

Here is a batch upgrade script that I managed to get working using something I found:
```python
import System
import clr
clr.AddReference("System.Core")
clr.ImportExtensions(System.Linq)

clr.AddReference("RevitAPI")
clr.AddReference("RevitAPIUI")
from Autodesk.Revit.DB import *

import revit_script_util
from revit_script_util import Output

from System.IO import Path
import revit_dynamo_util
import revit_file_util


# This should point to your Dynamo task script (*.dyn) file.
DYNAMO_SCRIPT_FILE_PATH = r"C:\BatchProcessing\MyDynamoTaskScript.dyn"

# Location to save the processed Revit files to.
SAVE_FOLDER_PATH = r"C:\out"


def SaveAsNewCentral(doc, modelPath, overwrite=True, clearTransmitted=False):
  saveAsOptions = SaveAsOptions()
  saveAsOptions.Compact = True
  saveAsOptions.OverwriteExistingFile = overwrite
  saveAsOptions.MaximumBackups = 1
  worksharingSaveAsOptions = WorksharingSaveAsOptions()
  worksharingSaveAsOptions.SaveAsCentral = True
  worksharingSaveAsOptions.ClearTransmitted = clearTransmitted
  saveAsOptions.SetWorksharingOptions(worksharingSaveAsOptions)
  doc.SaveAs(modelPath, saveAsOptions)
  return

def SaveRevitFile(doc, originalRevitFilePath, saveFolderPath):
  # Save the Revit model / family file in the new location.
  revitFileName = Path.GetFileName(originalRevitFilePath)
  saveRevitFilePath = Path.Combine(saveFolderPath, revitFileName)
  if doc.IsWorkshared: # For workshared models.
    saveRevitModelPath = ModelPathUtils.ConvertUserVisiblePathToModelPath(saveRevitFilePath)
    SaveAsNewCentral(
        doc,
        saveRevitModelPath,
        True, # NOTE: this means overwrite the existing file if it exists; set to False if this is not desired.
        True  # NOTE: this means clear the transmitted flag.
              # (This only works on transmitted files. It will cause an error for non-transmitted files!)
      )
    revit_file_util.RelinquishAll(doc) # Need to relinquish ownership of worksets after saving as new Central file.
  else: # For non-workshared models and family files.
    revit_file_util.SaveAs(
        doc,
        saveRevitFilePath,
        True # NOTE: this means overwrite the existing file if it exists; set to False if this is not desired.
      )
  return


sessionId = revit_script_util.GetSessionId()
uiapp = revit_script_util.GetUIApplication()

# NOTE: these only make sense for batch Revit file processing mode.
doc = revit_script_util.GetScriptDocument()
revitFilePath = revit_script_util.GetRevitFilePath()
projectFolderName = revit_script_util.GetProjectFolderName()

Output()
Output("This task script is running!")

# Execute the Dynamo script
# revit_dynamo_util.ExecuteDynamoScript(uiapp, DYNAMO_SCRIPT_FILE_PATH)

# Save the Revit file to the destination folder.
SaveRevitFile(doc, revitFilePath, SAVE_FOLDER_PATH)
```
