### ISSUE TITLE
No support for Revit 2022

### ISSUE THREAD

**Issue by guysoft** [bvn-architecture/RevitBatchProcessor#79]
Hey, any chance to add that?

Also in the building instructions - is there anything that can be changed to build it for version Revit 2022?

Thanks!

**Comment by NicklasOestergaard** [comment]
I'm not a programmer. I'm just a ‘constructing architect’ with a bit of a self-taught sense of C #. You can find my updated version here: https://github.com/NicklasOestergaard/RevitBatchProcessor
