### ISSUE TITLE
DOES NOT WORK FOR REVIT 2016

### ISSUE THREAD

**Issue by alexberd** [bvn-architecture/RevitBatchProcessor#8]
The image at https://github.com/bvn-architecture/RevitBatchProcessor/blob/master/BatchRvt_Screenshot.png shows that it can be also used with Revit 2015. However, for 2015 Revit Files, the following error message appears: "ERROR: All specified Revit Files are of an unsupported version or have an unsupported file path."

See below the whole report:

> 19:21:10 : 
> 19:21:10 : Session ID: <2018-04-17T18:21:10.431Z>
> 19:21:10 : 
> 19:21:10 : Log File:
> 19:21:10 : 
> 19:21:10 : 	C:\Users\alexberd\AppData\Local\BatchRvt\BatchRvt_20180417_192110_431.log
> 19:21:10 : 
> 19:21:10 : Task Script:
> 19:21:10 : 
> 19:21:10 : 	U:\Team\Dynamo Scripts\Main_9.dyn
> 19:21:10 : 
> 19:21:10 : Show Message Box on Task Script Error is enabled.
> 19:21:10 : 
> 19:21:10 : Revit Processing mode:
> 19:21:10 : 
> 19:21:10 : 	Batch Revit File processing
> 19:21:10 : 
> 19:21:10 : Reading Revit File list:
> 19:21:10 : 
> 19:21:10 : 	U:\Team\212.10\@Revit Batch Processor.txt
> 19:21:11 : 
> 19:21:11 : WARNING: The following Revit Files are of an unsupported version (1):
> 19:21:11 : 
> 19:21:11 : 	C:\test\-XX-XX-M3-A-TEST2.rvt
> 19:21:11 : 	File exists: YES
> 19:21:11 : 	File size: 7.96MB
> 19:21:11 : 	Revit version: Autodesk Revit Architecture 2016 (Build: 20151007_0715(x64))
> 19:21:11 : 
> 19:21:11 : ERROR: All specified Revit Files are of an unsupported version or have an unsupported file path.
> 19:21:11 : 
> 19:21:11 : Operation aborted.
> 19:21:11 : 
> 
> 

Any suggestion will be appreciated.
Kind regards,

**Comment by DanRumery** [comment]
Hi Alex

The file there says it's a Revit 2016 file (which would require that you have Revit 2016 or later installed). If you don't have Revit 2016 installed but have a later version then you can use the 'Use specific Revit version' option in the GUI.

Let me know if this is the case or not...

**Comment by DanRumery** [comment]
@alexberd 

Hi Alex

I've updated the installer with the fix. (v1.2.4):

https://github.com/bvn-architecture/RevitBatchProcessor/releases/tag/v.1.2.4

Can you please uninstall your previous version of the Revit Batch Processor, install this version and let me know if the update fixes this issue for you.

I've added support for the detection of 'Revit Architecture 2015' and 'Revit Architecture 2016' installation paths. Revit 2017 and later doesn't have a separate Architecture version so I've left those as is.

Regards.

**Comment by DanRumery** [comment]
Believed to be fixed. (still awaiting response from @alexberd)
