### ISSUE TITLE
Revit 2022 projects won't open.

### ISSUE THREAD

**Issue by ShinK360** [bvn-architecture/RevitBatchProcessor#90]
The tool opened Revit 2022 files and processed OK yesterday but, it is not working today. As soon as Revit 2022 opens, it closes. I use 1.7 version.
I uninstall the app and reinstalled. Cleared app data, but result was the same.

[BatchRvt_20220422_152200_844.txt](https://github.com/bvn-architecture/RevitBatchProcessor/files/8536626/BatchRvt_20220422_152200_844.txt)

**Comment by Coolicky** [comment]
The method "ConvertCloudGUIDsToCloudPath" has changed in the API for 2022.

https://www.revitapidocs.com/2021.1/cc284f13-a7a9-d37e-e46d-4769bf039a96.htm

**Comment by ShinK360** [comment]
Hi

Thank you for fixing the issue. I am so excited about that.
However, I am not a programmer and have no idea where to put the change into.

Would you be kind to tell me what file I should go and what to update to fix this, please?


Ngā Mihi

Shin Kameyama |  BIM Coordinator

architectus™ |  ***@***.*** <https://www.instagram.com/architectus.nz/>   | +64 9 307 5970  |  Auckland - Christchurch - Wellington  |   www.architectus.co.nz<http://www.architectus.co.nz/>

**Comment by Coolicky** [comment]
I haven't fixed the issue. I'm having the same problems with this as You would. 

The Guys from BVN have other commitments and do not have time to maintain this project I guess. I wish I could fix it but my python skills are very limited :). I will be trying to rewrite a lot of the code from python to C# and create a multi version configuration. However it may take some time as I can only do outside of my normal working hours.

**Comment by Coolicky** [comment]
@kraftwerk15 Hi. I would love to help on it if You're ok with it. I have some automation to be done at work and I would have to update RevitBatchProcessor either way.

Might be much better if I could get a head start. Throw me a message on piotr.kulicki@gmail.com. I think Github removed DM's.

**Comment by kraftwerk15** [comment]
@Coolicky This is over on GitLab. For others, this is a public repo. The largest portion that is not working would be using Python scripts on projects or families. The python library is still included in the build, but it wasn't something that I needed for my work flows. I was working towards something that I could setup a Windows Task to run this via command line along with a integer argument to go see if I updated a family in an earlier version in my library and upgrade to the latest versions.

Feel free to work with it as much as desired. If I ever find time to get back around to it, I'll work on it some.

[https://gitlab.com/kraftwerk15/revitmultiple](https://gitlab.com/kraftwerk15/revitmultiple)

**Comment by Coolicky** [comment]
@kraftwerk15 Thank You. Thank You. Will get to it asap. Real life is busy though :)

**Comment by ShinK360** [comment]
Thanks for picking up my request, but I am not actually following what is going on with this. Shall I wait and leave it with you 2 capable hands?? Revit 2023 capability would be great if you can add that at the same time!! Looking forward to hearing from you.

**Comment by punderscoresmithuk** [comment]
Hi all, this should be fixed with the latest release of RBP. Please advise if not however
